@startuml Sistema-Bibliotecario-Funcionales
left to right direction

actor Usuario
actor Bibliotecario
actor "Sistema de Notificación"

rectangle "Sistema General de Biblioteca" {
    usecase "Registrar Usuario" as CU1
    usecase "Login" as CU2
    usecase "Verificar Credenciales" as CU3
    usecase "Gestionar Usuario" as CU4
    usecase "Buscar Libro" as CU5
    usecase "Reservar Libro" as CU6
    usecase "Notificar Usuario" as CU7
    usecase "Enviar Notificación" as CU8
    usecase "Consultar Historial" as CU9
    usecase "Administrar Inventario" as CU10
    usecase "Añadir Libro" as CU11
    usecase "Borrar Libro" as CU12
    usecase "Modificar Libro" as CU13
    usecase "Gestionar Devolución" as CU14
    usecase "Enviar Autenticación" as CU15
}

Usuario --> CU1
Usuario --> CU2
Usuario --> CU4
Usuario --> CU5
Usuario --> CU6
Usuario --> CU9

CU2 -.> CU3 : include
CU6 -.> CU7 : extend
CU7 -.> CU8 : include

Bibliotecario --> CU1
Bibliotecario --> CU2
Bibliotecario --> CU4
Bibliotecario --> CU5
Bibliotecario --> CU6
Bibliotecario --> CU9
Bibliotecario --> CU10

CU10 -.> CU11 : include
CU10 -.> CU12 : include
CU10 -.> CU13 : include
CU1 -.> CU2 : extend

Bibliotecario --> CU14

"Sistema de Notificación" -- CU8
"Sistema de Notificación" -- CU15

CU1 -.> CU15 : include

@enduml